#!/usr/bin/env bash
# Configure a ufw firewall to block incoming traffic
# except fot TCP ports 22, 80, 443

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable

